AWSTemplateFormatVersion: "2010-09-09"
Description: Setup infra for fine-processor system (code commit, ECR, S3)
Resources:
  FileExtractorECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "file-extractor"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::573128978443:user/doug"
#                - "arn:aws:codebuild:ap-southeast-2:573128978443:project/file-extractor"
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
